Homework 1
LogExE/tinkofftasks pull request #1
Opened 2023-10-15 10:07 UTC by LogExE

2023-10-15 19:38 UTC, psharaev requested changes
Пометки:
🔴 Критичные комментарии, необходимо всех их устранить;
🟡 Общепринятый стиль написания кода на Java, так же обязательно к исправлению;
🟢 Нетривиальные правки и без них поставлю полный балл, но я порадуюсь, если вы их сделаете.

2023-10-15 19:38 UTC, psharaev commented on src/main/java/edu/hw1/Task1.java
> +        long mins, secs;
🟡 Не объявляйте переменные через запятую. Объявляйте каждую на новой строке.
```
long mins;
long secs;
```
🟡 Не надо подавлять `@SuppressWarnings("MultipleVariableDeclarations")`

2023-10-15 19:38 UTC, psharaev commented on src/main/java/edu/hw1/Task2.java
> +        x = Math.abs(x);
🔴 К сожалению, `Math.abs` здесь может повести себя неожиданным способом. Поскольку
`-Integer.MIN_VALUE == Integer.MIN_VALUE` и тогда `countDigits(Integer.MIN_VALUE)` вернёт неправильный результат.
Заифайте этот случай, напишите другой алгоритм или используйте `Math.absExact`

2023-10-15 19:38 UTC, psharaev commented on src/main/java/edu/hw1/Task3.java
> +    @SuppressWarnings("MultipleVariableDeclarations")
🟡 Аналогично не надо подавлять `@SuppressWarnings("MultipleVariableDeclarations")z

2023-10-15 19:38 UTC, psharaev commented on src/main/java/edu/hw1/Task3.java
> +            if (j < min1) {
🟢 Хорошее решение, но над ним надо думать, чтобы убедиться правильно ли тут расставлены сравнения, те ли переменные читаются/записываются и т.п.

Далее по курсу я надеюсь вас познакомят со Stream API в Java, тогда можно было бы компактнее написать (и что главное думать не надо, а значит меньше шанс получить багу)
`int array1MaxValue = Arrays.stream(array1).max().getAsInt();`

2023-10-15 19:38 UTC, psharaev commented on src/main/java/edu/hw1/Task4.java
> +            res += toFix.charAt(Math.min(i + add, len - 1));
🔴 Конкатенация строк работает медленно, используйте `StringBuilder`

2023-10-15 19:38 UTC, psharaev commented on src/test/java/edu/hw1/Task1Test.java
> +        assertThat(res1).isEqualTo(30);
🟡 Можно написать короче 
`import static org.junit.jupiter.api.Assertions.assertEquals;`
`assertEquals(res1, 30);`
Аналогично везде

2023-10-16 03:54 UTC, LogExE commented on src/test/java/edu/hw1/Task1Test.java
> +        assertThat(res1).isEqualTo(30);
Исправил. Раньше использовал assertThat так как в пункте "1.3 Настройка рабочего окружения" курса рекомендовалось использовать assertj

2023-10-20 07:55 UTC, psharaev commented
Принято. У меня нет прав на слияние PR. Можете, пожалуйста, влить

2023-10-20 08:59 UTC, merged