Homework 2
LogExE/tinkofftasks pull request #2
Opened 2023-10-22 10:06 UTC by LogExE

2023-10-23 20:23 UTC, psharaev requested changes
Пометки:
🔴 Критичные комментарии, необходимо всех их устранить;
🟡 Общепринятый стиль написания кода на Java, так же обязательно к исправлению;
🟢 Нетривиальные правки и без них поставлю полный балл, но я порадуюсь, если вы их сделаете.

2023-10-23 20:23 UTC, psharaev commented on src/main/java/edu/hw2/task2/Rectangle.java
> +    private int height;
🔴 Классы должны быть имутабельными, для этого к полям добавьте `final`
🔴 Сделайте конструктор `Rectangle(length, width)`

2023-10-23 20:23 UTC, psharaev commented on src/main/java/edu/hw2/task2/Rectangle.java
> +        ret.width = width;
🔴 Измените семантику метода и аналогичные ему
```
public Rectangle setWidth(int width) {
    return new Rectangle(height, width);
}
```

2023-10-23 20:23 UTC, psharaev commented on src/main/java/edu/hw2/task3/ConnectionException.java
> +
🟢 Стоит добавить какие-то из этих конструкторов, что бы сообщать пользователю сообщение об ошибке и оригинальное исключение
```
public ConnectionException() {
    super();
}

public ConnectionException(String message) {
    super(message);
}

public ConnectionException(Throwable cause) {
    super(cause);
}

public ConnectionException(String message, Throwable cause) {
    super(message, cause);
}
```

2023-10-23 20:23 UTC, psharaev commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +                    cause = conEx;
🟢 Стоит собирать исключения, которые так же происходили и не затирать их
```
ConnectionException exc = null;
```
```
if (exc == null) {
    exc = ex;
} else {
    exc.addSuppressed(ex);
}
```
```
if (exc != null) {
    throw exc;
}
```

2023-10-23 20:23 UTC, psharaev commented on src/main/java/edu/hw2/task4/Task4.java
> +            StackTraceElement[] stack = ex.getStackTrace();
🔴 В задании опечатка, подразумевалось использование `Thread.currentThread().getStackTrace();`

2023-10-24 19:20 UTC, psharaev commented
https://github.com/LogExE/tinkofftasks/pull/2

2023-10-25 05:07 UTC, LogExE commented
> https://github.com/LogExE/tinkofftasks/pull/2

Меня перекидывает на эту же страницу. Это значит нужно еще что-то доделать, или...?

2023-10-25 07:09 UTC, psharaev commented
Принято

2023-10-25 07:35 UTC, merged