Project 1: Виселица
LogExE/tinkofftasks pull request #3
Opened 2023-10-22 14:20 UTC by LogExE

2023-10-24 17:59 UTC, psharaev requested changes

2023-10-24 17:59 UTC, psharaev commented on src/main/java/edu/project1/ConsoleHangman.java
> +                new InputStreamReader(System.in));
Используйте try-with-resources

2023-10-24 17:59 UTC, psharaev commented on src/main/java/edu/project1/ConsoleHangman.java
> +                    GuessResult guessResult = tryGuess(session, line);
Пожалуй, хорошей будет декомпозицией создание класса HangmanGame (всё же играть в виселицу можно не только в консоли), которому в конструктор можно будет передать игрока.

1. Следует создать интерфейс игрока с достаточно похожим методом `tryGuess`. Создать класс HumanPlayer (или ConsolePlayer). Если захотите можете для себя создать RandomPlayer;

Такая декомпзиция позволит вам очень ловко создавать различные конфигурации игры, не сильно меняя код

2023-10-26 06:40 UTC, LogExE commented
Насчет try-with-resources: теперь у меня класс ConsoleHangman держит BufferedReader в качестве поля и не особо ясно когда именно нужно закрывать поток ввода. Нужно ли делать ConsoleHangman реализующим AutoClosable?

2023-10-26 08:58 UTC, psharaev commented
> Насчет try-with-resources: теперь у меня класс ConsoleHangman держит BufferedReader в качестве поля и не особо ясно когда именно нужно закрывать поток ввода. Нужно ли делать ConsoleHangman реализующим AutoClosable?

Есть несколько путей решения этого
1. Передавать в ConsoleHangman уже открытый поток, тогда снаружи это будет выглядеть примерно так:
```
try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in))) {
    HangmanPlayer player = new ConsoleHangman(reader);
    /* ... */
} catch (IOException e) {
    throw new RuntimeException(e);
}
```
2. Сделать ConsoleHangman AutoClosable, тогда снаружи это будет примерно так:
```
try (HangmanPlayer player = new ConsoleHangman()){
    /* ... */
} catch(Exception e){
    throw new RuntimeException(e);
}
```
В целом что вы выберите мне не принципиально (хотя первый способ мне нравится больше т.к. снаружи будет большо контроля и можно подсунуть какой-нибудь стрим для тестов)

На самом деле эти два способа почти эквивалентны, при следующей реализации ConsoleHangman:
```
public class ConsoleHangman implements AutoCloseable {
    private final BufferedReader reader;

    public ConsoleHangman() {
        this(new BufferedReader(new InputStreamReader(System.in)));
    }

    public ConsoleHangman(BufferedReader reader) {
        this.reader = reader;
    }

    @Override
    public void close() throws Exception {
        reader.close();
    }
}
```
Правда, если использовать конструктор по умолчанию, при вызове close(), закроется System.in, но это не точно (я верю что вы сможете самостоятельно провести эксперимент насчёт этого)

2023-10-26 08:59 UTC, psharaev commented
Принято. У меня нет прав на слияние PR. Можете, пожалуйста, влить

2023-10-26 09:51 UTC, merged