Homework 3
LogExE/tinkofftasks pull request #4
Opened 2023-10-29 07:13 UTC by LogExE

2023-10-30 20:20 UTC, psharaev requested changes
Пометки:
🔴 Критичные комментарии, необходимо всех их устранить;
🟡 Общепринятый стиль написания кода на Java, так же обязательно к исправлению;
🟢 Нетривиальные правки и без них поставлю полный балл, но я порадуюсь, если вы их сделаете.

2023-10-30 20:20 UTC, psharaev commented on src/main/java/edu/hw3/task5/Contact.java
> +        return ours.compareTo(theirs);
🔴 Обычно компараторы пишут в декларативном стиле. Не надо здесь реализовывать `Comparable`
```java
private static final Comparator<Contact> ASC = Comparator
        .comparing(Contact::surname)
        .thenComparing(Contact::name);
private static final Comparator<Contact> DESC = ASC.reversed();
```

2023-10-30 20:20 UTC, psharaev commented on src/main/java/edu/hw3/task8/BackwardsIterator.java
> +            stack.push(el);
🔴 Не надо использовать `Stack`, неожиданно, но он работает медленно т.к. берёт блокировку под капотом. Сделайте копию коллекции в лист

2023-10-30 20:38 UTC, LogExE commented on src/main/java/edu/hw3/task5/Contact.java
> +        return ours.compareTo(theirs);
как же тогда быть с null значениями?

2023-11-01 13:57 UTC, psharaev commented
Принято. У меня нет прав на слияние PR. Можете, пожалуйста, сделать merge

2023-11-01 14:10 UTC, merged